package models

import (
	"fmt"
	"time"

	"github.com/jinzhu/gorm"
)

// ===== BEGIN of all query sets

// ===== BEGIN of query set NotifierItemQuerySet

// NotifierItemQuerySet is an queryset type for NotifierItem
type NotifierItemQuerySet struct {
	db *gorm.DB
}

// NewNotifierItemQuerySet constructs new NotifierItemQuerySet
func NewNotifierItemQuerySet(db *gorm.DB) NotifierItemQuerySet {
	return NotifierItemQuerySet{
		db: db.Model(&NotifierItem{}),
	}
}

func (qs NotifierItemQuerySet) w(db *gorm.DB) NotifierItemQuerySet {
	return NewNotifierItemQuerySet(db)
}

// APIKeyEq is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) APIKeyEq(aPIKey string) NotifierItemQuerySet {
	return qs.w(qs.db.Where("api_key = ?", aPIKey))
}

// APIKeyIn is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) APIKeyIn(aPIKey string, aPIKeyRest ...string) NotifierItemQuerySet {
	iArgs := []interface{}{aPIKey}
	for _, arg := range aPIKeyRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("api_key IN (?)", iArgs))
}

// APIKeyNe is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) APIKeyNe(aPIKey string) NotifierItemQuerySet {
	return qs.w(qs.db.Where("api_key != ?", aPIKey))
}

// APIKeyNotIn is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) APIKeyNotIn(aPIKey string, aPIKeyRest ...string) NotifierItemQuerySet {
	iArgs := []interface{}{aPIKey}
	for _, arg := range aPIKeyRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("api_key NOT IN (?)", iArgs))
}

// All is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) All(ret interface{}) error {
	return qs.db.Debug().Find(ret).Error
}

// Count is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) Count() (int, error) {
	var count int
	err := qs.db.Count(&count).Error
	return count, err
}

// Create is an autogenerated method
// nolint: dupl
func (o *NotifierItem) Create(db *gorm.DB) error {
	return db.Create(o).Error
}

// CreatedAtEq is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) CreatedAtEq(createdAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("created_at = ?", createdAt))
}

// CreatedAtGt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) CreatedAtGt(createdAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("created_at > ?", createdAt))
}

// CreatedAtGte is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) CreatedAtGte(createdAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("created_at >= ?", createdAt))
}

// CreatedAtLt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) CreatedAtLt(createdAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("created_at < ?", createdAt))
}

// CreatedAtLte is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) CreatedAtLte(createdAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("created_at <= ?", createdAt))
}

// CreatedAtNe is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) CreatedAtNe(createdAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("created_at != ?", createdAt))
}

// Delete is an autogenerated method
// nolint: dupl
func (o *NotifierItem) Delete(db *gorm.DB) error {
	return db.Delete(o).Error
}

// Delete is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) Delete() error {
	return qs.db.Delete(NotifierItem{}).Error
}

// DeletedAtEq is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) DeletedAtEq(deletedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("deleted_at = ?", deletedAt))
}

// DeletedAtGt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) DeletedAtGt(deletedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("deleted_at > ?", deletedAt))
}

// DeletedAtGte is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) DeletedAtGte(deletedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("deleted_at >= ?", deletedAt))
}

// DeletedAtIsNotNull is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) DeletedAtIsNotNull() NotifierItemQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NOT NULL"))
}

// DeletedAtIsNull is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) DeletedAtIsNull() NotifierItemQuerySet {
	return qs.w(qs.db.Where("deleted_at IS NULL"))
}

// DeletedAtLt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) DeletedAtLt(deletedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("deleted_at < ?", deletedAt))
}

// DeletedAtLte is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) DeletedAtLte(deletedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("deleted_at <= ?", deletedAt))
}

// DeletedAtNe is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) DeletedAtNe(deletedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("deleted_at != ?", deletedAt))
}

// GetUpdater is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) GetUpdater() NotifierItemUpdater {
	return NewNotifierItemUpdater(qs.db)
}

// IDEq is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) IDEq(ID uint) NotifierItemQuerySet {
	return qs.w(qs.db.Where("id = ?", ID))
}

// IDGt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) IDGt(ID uint) NotifierItemQuerySet {
	return qs.w(qs.db.Where("id > ?", ID))
}

// IDGte is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) IDGte(ID uint) NotifierItemQuerySet {
	return qs.w(qs.db.Where("id >= ?", ID))
}

// IDIn is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) IDIn(ID uint, IDRest ...uint) NotifierItemQuerySet {
	iArgs := []interface{}{ID}
	for _, arg := range IDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("id IN (?)", iArgs))
}

// IDLt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) IDLt(ID uint) NotifierItemQuerySet {
	return qs.w(qs.db.Where("id < ?", ID))
}

// IDLte is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) IDLte(ID uint) NotifierItemQuerySet {
	return qs.w(qs.db.Where("id <= ?", ID))
}

// IDNe is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) IDNe(ID uint) NotifierItemQuerySet {
	return qs.w(qs.db.Where("id != ?", ID))
}

// IDNotIn is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) IDNotIn(ID uint, IDRest ...uint) NotifierItemQuerySet {
	iArgs := []interface{}{ID}
	for _, arg := range IDRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("id NOT IN (?)", iArgs))
}

// Limit is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) Limit(limit int) NotifierItemQuerySet {
	return qs.w(qs.db.Limit(limit))
}

// NameEq is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) NameEq(name string) NotifierItemQuerySet {
	return qs.w(qs.db.Where("name = ?", name))
}

// NameIn is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) NameIn(name string, nameRest ...string) NotifierItemQuerySet {
	iArgs := []interface{}{name}
	for _, arg := range nameRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("name IN (?)", iArgs))
}

// NameNe is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) NameNe(name string) NotifierItemQuerySet {
	return qs.w(qs.db.Where("name != ?", name))
}

// NameNotIn is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) NameNotIn(name string, nameRest ...string) NotifierItemQuerySet {
	iArgs := []interface{}{name}
	for _, arg := range nameRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("name NOT IN (?)", iArgs))
}

// One is used to retrieve one result. It returns gorm.ErrRecordNotFound
// if nothing was fetched
func (qs NotifierItemQuerySet) One(ret *NotifierItem) error {
	return qs.db.First(ret).Error
}

// OrderAscByCreatedAt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) OrderAscByCreatedAt() NotifierItemQuerySet {
	return qs.w(qs.db.Order("created_at ASC"))
}

// OrderAscByDeletedAt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) OrderAscByDeletedAt() NotifierItemQuerySet {
	return qs.w(qs.db.Order("deleted_at ASC"))
}

// OrderAscByID is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) OrderAscByID() NotifierItemQuerySet {
	return qs.w(qs.db.Order("id ASC"))
}

// OrderAscByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) OrderAscByUpdatedAt() NotifierItemQuerySet {
	return qs.w(qs.db.Order("updated_at ASC"))
}

// OrderDescByCreatedAt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) OrderDescByCreatedAt() NotifierItemQuerySet {
	return qs.w(qs.db.Order("created_at DESC"))
}

// OrderDescByDeletedAt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) OrderDescByDeletedAt() NotifierItemQuerySet {
	return qs.w(qs.db.Order("deleted_at DESC"))
}

// OrderDescByID is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) OrderDescByID() NotifierItemQuerySet {
	return qs.w(qs.db.Order("id DESC"))
}

// OrderDescByUpdatedAt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) OrderDescByUpdatedAt() NotifierItemQuerySet {
	return qs.w(qs.db.Order("updated_at DESC"))
}

// ProviderEq is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) ProviderEq(provider string) NotifierItemQuerySet {
	return qs.w(qs.db.Where("provider = ?", provider))
}

// ProviderIn is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) ProviderIn(provider string, providerRest ...string) NotifierItemQuerySet {
	iArgs := []interface{}{provider}
	for _, arg := range providerRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("provider IN (?)", iArgs))
}

// ProviderNe is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) ProviderNe(provider string) NotifierItemQuerySet {
	return qs.w(qs.db.Where("provider != ?", provider))
}

// ProviderNotIn is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) ProviderNotIn(provider string, providerRest ...string) NotifierItemQuerySet {
	iArgs := []interface{}{provider}
	for _, arg := range providerRest {
		iArgs = append(iArgs, arg)
	}
	return qs.w(qs.db.Where("provider NOT IN (?)", iArgs))
}

// SetAPIKey is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) SetAPIKey(aPIKey string) NotifierItemUpdater {
	u.fields[string(NotifierItemDBSchema.APIKey)] = aPIKey
	return u
}

// SetCreatedAt is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) SetCreatedAt(createdAt time.Time) NotifierItemUpdater {
	u.fields[string(NotifierItemDBSchema.CreatedAt)] = createdAt
	return u
}

// SetDeletedAt is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) SetDeletedAt(deletedAt *time.Time) NotifierItemUpdater {
	u.fields[string(NotifierItemDBSchema.DeletedAt)] = deletedAt
	return u
}

// SetID is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) SetID(ID uint) NotifierItemUpdater {
	u.fields[string(NotifierItemDBSchema.ID)] = ID
	return u
}

// SetName is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) SetName(name string) NotifierItemUpdater {
	u.fields[string(NotifierItemDBSchema.Name)] = name
	return u
}

// SetProvider is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) SetProvider(provider string) NotifierItemUpdater {
	u.fields[string(NotifierItemDBSchema.Provider)] = provider
	return u
}

// SetUpdatedAt is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) SetUpdatedAt(updatedAt time.Time) NotifierItemUpdater {
	u.fields[string(NotifierItemDBSchema.UpdatedAt)] = updatedAt
	return u
}

// Update is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) Update() error {
	return u.db.Updates(u.fields).Error
}

// UpdateNum is an autogenerated method
// nolint: dupl
func (u NotifierItemUpdater) UpdateNum() (int64, error) {
	db := u.db.Updates(u.fields)
	return db.RowsAffected, db.Error
}

// UpdatedAtEq is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) UpdatedAtEq(updatedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("updated_at = ?", updatedAt))
}

// UpdatedAtGt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) UpdatedAtGt(updatedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("updated_at > ?", updatedAt))
}

// UpdatedAtGte is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) UpdatedAtGte(updatedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("updated_at >= ?", updatedAt))
}

// UpdatedAtLt is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) UpdatedAtLt(updatedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("updated_at < ?", updatedAt))
}

// UpdatedAtLte is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) UpdatedAtLte(updatedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("updated_at <= ?", updatedAt))
}

// UpdatedAtNe is an autogenerated method
// nolint: dupl
func (qs NotifierItemQuerySet) UpdatedAtNe(updatedAt time.Time) NotifierItemQuerySet {
	return qs.w(qs.db.Where("updated_at != ?", updatedAt))
}

// ===== END of query set NotifierItemQuerySet

// ===== BEGIN of NotifierItem modifiers

type notifierItemDBSchemaField string

func (f notifierItemDBSchemaField) String() string {
	return string(f)
}

// NotifierItemDBSchema stores db field names of NotifierItem
var NotifierItemDBSchema = struct {
	ID        notifierItemDBSchemaField
	CreatedAt notifierItemDBSchemaField
	UpdatedAt notifierItemDBSchemaField
	DeletedAt notifierItemDBSchemaField
	Name      notifierItemDBSchemaField
	Provider  notifierItemDBSchemaField
	APIKey    notifierItemDBSchemaField
}{

	ID:        notifierItemDBSchemaField("id"),
	CreatedAt: notifierItemDBSchemaField("created_at"),
	UpdatedAt: notifierItemDBSchemaField("updated_at"),
	DeletedAt: notifierItemDBSchemaField("deleted_at"),
	Name:      notifierItemDBSchemaField("name"),
	Provider:  notifierItemDBSchemaField("provider"),
	APIKey:    notifierItemDBSchemaField("api_key"),
}

// Update updates NotifierItem fields by primary key
func (o *NotifierItem) Update(db *gorm.DB, fields ...notifierItemDBSchemaField) error {
	dbNameToFieldName := map[string]interface{}{
		"id":         o.ID,
		"created_at": o.CreatedAt,
		"updated_at": o.UpdatedAt,
		"deleted_at": o.DeletedAt,
		"name":       o.Name,
		"provider":   o.Provider,
		"api_key":    o.APIKey,
	}
	u := map[string]interface{}{}
	for _, f := range fields {
		fs := f.String()
		u[fs] = dbNameToFieldName[fs]
	}
	if err := db.Model(o).Updates(u).Error; err != nil {
		if err == gorm.ErrRecordNotFound {
			return err
		}

		return fmt.Errorf("can't update NotifierItem %v fields %v: %s",
			o, fields, err)
	}

	return nil
}

// NotifierItemUpdater is an NotifierItem updates manager
type NotifierItemUpdater struct {
	fields map[string]interface{}
	db     *gorm.DB
}

// NewNotifierItemUpdater creates new NotifierItem updater
func NewNotifierItemUpdater(db *gorm.DB) NotifierItemUpdater {
	return NotifierItemUpdater{
		fields: map[string]interface{}{},
		db:     db.Model(&NotifierItem{}),
	}
}

// ===== END of NotifierItem modifiers

// ===== END of all query sets
